/// MVP Phase 1 seed data definitions for the Knowledge Graph.
///
/// Mirrors `supabase/migrations/20260716000003_seed_knowledge_graph_mvp.sql`
/// plus George Aug 28 graph holes (`20260828000001_george_graph_seed_fixes.sql`).
/// Used by [KnowledgeGraphSeeder] for programmatic seeding via service role.

/// Graph version tag for all MVP Phase 1 content.
const kgMvpVersion = 'KG-v0.1-mvp';

/// Default metadata attached to every seeded node.
const kgMvpSourceMeta = {
  'source': 'MVP Phase 1 seed',
  'reviewed': '2026-07-16',
  'phase': 1,
};

/// Node seed record.
class KgSeedNode {
  const KgSeedNode({
    required this.type,
    required this.slug,
    required this.name,
    this.description,
    this.metadata = const {},
  });

  final String type;
  final String slug;
  final String name;
  final String? description;
  final Map<String, dynamic> metadata;
}

/// Edge seed record — references nodes by slug + type.
///
/// [relation] is the real graph relation (`contains`, `applies_to`, `affects`,
/// `suggests`, `produces`). The seeder must persist this value as-is.
class KgSeedEdge {
  const KgSeedEdge({
    required this.sourceType,
    required this.sourceSlug,
    required this.targetType,
    required this.targetSlug,
    required this.relation,
    this.weight = 0.5,
    this.note,
  });

  final String sourceType;
  final String sourceSlug;
  final String targetType;
  final String targetSlug;
  final String relation;
  final double weight;
  final String? note;
}

/// All nodes the Dart seeder writes. Slugs match SQL.
final kgMvpNodes = <KgSeedNode>[
  const KgSeedNode(
    type: 'appliance_category',
    slug: 'dishwasher',
    name: 'Dishwasher',
  ),
  const KgSeedNode(
    type: 'appliance_category',
    slug: 'washing-machine',
    name: 'Washing Machine',
  ),
  const KgSeedNode(type: 'appliance_category', slug: 'dryer', name: 'Dryer'),
  const KgSeedNode(
    type: 'appliance_category',
    slug: 'refrigerator-freezer',
    name: 'Refrigerator / Freezer',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'dishwasher-drain-system',
    name: 'Drain System',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'dishwasher-water-supply',
    name: 'Water Supply',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'washer-drive-spin',
    name: 'Drive & Spin',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'washer-drain-system',
    name: 'Drain System',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'dryer-heating',
    name: 'Heating System',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'dryer-drive-system',
    name: 'Drive System',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'dryer-door-latch',
    name: 'Door & Latch',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'refrigerator-cooling',
    name: 'Cooling System',
  ),
  const KgSeedNode(
    type: 'subsystem',
    slug: 'refrigerator-defrost',
    name: 'Defrost System',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dishwasher-drain-pump',
    name: 'Drain Pump',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dishwasher-drain-hose',
    name: 'Drain Hose',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dishwasher-float-switch',
    name: 'Float Switch',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dishwasher-door-seal',
    name: 'Door Seal',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'washer-lid-switch',
    name: 'Lid/Door Switch',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'washer-suspension',
    name: 'Tub suspension',
    description: 'Springs, rods, or dampers that hold the tub.',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'washer-drain-pump',
    name: 'Drain Pump',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'washer-drain-hose',
    name: 'Drain Hose',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dryer-thermal-fuse',
    name: 'Thermal Fuse',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dryer-drum-belt',
    name: 'Drum Belt',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dryer-door-switch',
    name: 'Door Switch',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'dryer-heating-element',
    name: 'Heating Element',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'refrigerator-evaporator-coils',
    name: 'Evaporator Coils',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'refrigerator-compressor',
    name: 'Compressor',
  ),
  const KgSeedNode(
    type: 'component',
    slug: 'refrigerator-drip-pan',
    name: 'Drip pan',
    description: 'Catches defrost water under the cabinet.',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'standing-water',
    name: 'Standing water after cycle',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'wont-drain',
    name: 'Water will not drain',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'wont-start',
    name: 'Will not start',
    description: 'Nothing happens when you try to start a cycle.',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'wont-fill',
    name: 'Will not fill with water',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'grinding-noise',
    name: 'Grinding or humming noise',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'water-leak-on-floor',
    name: 'Water on the floor',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'clothes-not-drying',
    name: 'Clothes still damp after cycle',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'drum-does-not-turn',
    name: 'Motor runs, drum does not turn',
    description:
        'You can hear the motor but the dryer drum stays still. Not a no-start.',
  ),
  const KgSeedNode(
    type: 'symptom',
    slug: 'not-cooling',
    name: 'Not keeping food cold enough',
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dishwasher-drain-obstruction',
    name: 'Drain path obstruction',
    metadata: {'difficulty': 'beginner', 'category': 'dishwasher'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dishwasher-drain-pump-failure',
    name: 'Drain pump not moving water',
    metadata: {'difficulty': 'intermediate', 'category': 'dishwasher'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dishwasher-door-seal-leak',
    name: 'Door seal leaking',
    metadata: {'difficulty': 'beginner', 'category': 'dishwasher'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dishwasher-drain-hose-leak',
    name: 'Drain hose leak or loose connection',
    metadata: {'difficulty': 'beginner', 'category': 'dishwasher'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dishwasher-float-switch-stuck',
    name: 'Float switch stuck or failed',
    description:
        'The float is jammed up (won’t fill) or stuck down (overfill / standing water). Look-only; do not bypass the switch.',
    metadata: {'difficulty': 'beginner', 'category': 'dishwasher'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-drain-clog',
    name: 'Drain clog or blockage',
    metadata: {'difficulty': 'beginner', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-drain-pump-failure',
    name: 'Drain pump debris or failure',
    description: 'Debris in the washer pump can grind; not a dryer failure.',
    metadata: {'difficulty': 'intermediate', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-drain-hose-leak',
    name: 'Drain hose leak',
    metadata: {'difficulty': 'beginner', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-supply-line-leak',
    name: 'Supply hose leak',
    metadata: {'difficulty': 'beginner', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-lid-switch-failure',
    name: 'Lid or door switch not closed',
    metadata: {'difficulty': 'beginner', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'washer-unbalanced-load',
    name: 'Unbalanced load',
    metadata: {'difficulty': 'beginner', 'category': 'washing-machine'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dryer-lint-buildup',
    name: 'Lint restriction',
    metadata: {'difficulty': 'beginner', 'category': 'dryer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dryer-worn-drum-belt',
    name: 'Worn or broken drum belt',
    description: 'Motor may run while the drum stays still.',
    metadata: {'difficulty': 'intermediate', 'category': 'dryer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dryer-thermal-fuse-open',
    name: 'Open thermal fuse',
    description:
        'The thermal fuse opened after overheating, often from restricted airflow. Not a generic won’t-start guess via a note on lint.',
    metadata: {'difficulty': 'intermediate', 'category': 'dryer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dryer-door-switch-failure',
    name: 'Door switch not closing the start circuit',
    description:
        'Nothing happens when you press start because the door switch does not see the door closed.',
    metadata: {'difficulty': 'beginner', 'category': 'dryer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'dryer-heating-element-failure',
    name: 'Heating element not producing heat',
    metadata: {'difficulty': 'intermediate', 'category': 'dryer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'refrigerator-dirty-condenser-coils',
    name: 'Dirty condenser coils',
    metadata: {'difficulty': 'beginner', 'category': 'refrigerator-freezer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'refrigerator-drip-pan-overflow',
    name: 'Drip pan overflow or blocked defrost drain',
    metadata: {'difficulty': 'beginner', 'category': 'refrigerator-freezer'},
  ),
  const KgSeedNode(
    type: 'failure_mode',
    slug: 'refrigerator-compressor-sealed-fault',
    name: 'Sealed-system compressor fault',
    description:
        'A compressor that will not pump is sealed-system work. Not a beginner DIY hypothesis.',
    metadata: {
      'difficulty': 'professional',
      'safety': 'sealed_system',
      'safety_gate': 'professional_sealed',
      'beginner_diy': false,
      'category': 'refrigerator-freezer',
    },
  ),
];

/// Authored edges. Relation types are persisted as written — no force-to-suggests.
final kgMvpEdges = <KgSeedEdge>[
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'dishwasher',
    targetType: 'subsystem',
    targetSlug: 'dishwasher-drain-system',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'dishwasher',
    targetType: 'subsystem',
    targetSlug: 'dishwasher-water-supply',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'washing-machine',
    targetType: 'subsystem',
    targetSlug: 'washer-drive-spin',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'washing-machine',
    targetType: 'subsystem',
    targetSlug: 'washer-drain-system',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'dryer',
    targetType: 'subsystem',
    targetSlug: 'dryer-heating',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'dryer',
    targetType: 'subsystem',
    targetSlug: 'dryer-drive-system',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'dryer',
    targetType: 'subsystem',
    targetSlug: 'dryer-door-latch',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'refrigerator-freezer',
    targetType: 'subsystem',
    targetSlug: 'refrigerator-cooling',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'appliance_category',
    sourceSlug: 'refrigerator-freezer',
    targetType: 'subsystem',
    targetSlug: 'refrigerator-defrost',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dishwasher-drain-system',
    targetType: 'component',
    targetSlug: 'dishwasher-drain-pump',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dishwasher-drain-system',
    targetType: 'component',
    targetSlug: 'dishwasher-drain-hose',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dishwasher-water-supply',
    targetType: 'component',
    targetSlug: 'dishwasher-float-switch',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'washer-drive-spin',
    targetType: 'component',
    targetSlug: 'washer-suspension',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'washer-drain-system',
    targetType: 'component',
    targetSlug: 'washer-drain-pump',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dryer-heating',
    targetType: 'component',
    targetSlug: 'dryer-thermal-fuse',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dryer-door-latch',
    targetType: 'component',
    targetSlug: 'dryer-door-switch',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'dryer-drive-system',
    targetType: 'component',
    targetSlug: 'dryer-drum-belt',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'refrigerator-cooling',
    targetType: 'component',
    targetSlug: 'refrigerator-evaporator-coils',
    relation: 'contains',
    weight: 1,
    note: 'Evaporator belongs under cooling, not defrost-only',
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'refrigerator-defrost',
    targetType: 'component',
    targetSlug: 'refrigerator-evaporator-coils',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'refrigerator-cooling',
    targetType: 'component',
    targetSlug: 'refrigerator-compressor',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'subsystem',
    sourceSlug: 'refrigerator-cooling',
    targetType: 'component',
    targetSlug: 'refrigerator-drip-pan',
    relation: 'contains',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-drain-pump-failure',
    targetType: 'appliance_category',
    targetSlug: 'dishwasher',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-drain-obstruction',
    targetType: 'appliance_category',
    targetSlug: 'dishwasher',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-door-seal-leak',
    targetType: 'appliance_category',
    targetSlug: 'dishwasher',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-drain-hose-leak',
    targetType: 'appliance_category',
    targetSlug: 'dishwasher',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-float-switch-stuck',
    targetType: 'appliance_category',
    targetSlug: 'dishwasher',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-drain-clog',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-drain-pump-failure',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-drain-hose-leak',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-supply-line-leak',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-lid-switch-failure',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-unbalanced-load',
    targetType: 'appliance_category',
    targetSlug: 'washing-machine',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-lint-buildup',
    targetType: 'appliance_category',
    targetSlug: 'dryer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-worn-drum-belt',
    targetType: 'appliance_category',
    targetSlug: 'dryer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-thermal-fuse-open',
    targetType: 'appliance_category',
    targetSlug: 'dryer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-door-switch-failure',
    targetType: 'appliance_category',
    targetSlug: 'dryer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-heating-element-failure',
    targetType: 'appliance_category',
    targetSlug: 'dryer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'refrigerator-dirty-condenser-coils',
    targetType: 'appliance_category',
    targetSlug: 'refrigerator-freezer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'refrigerator-drip-pan-overflow',
    targetType: 'appliance_category',
    targetSlug: 'refrigerator-freezer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'refrigerator-compressor-sealed-fault',
    targetType: 'appliance_category',
    targetSlug: 'refrigerator-freezer',
    relation: 'applies_to',
    weight: 1,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-lid-switch-failure',
    targetType: 'component',
    targetSlug: 'washer-lid-switch',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-unbalanced-load',
    targetType: 'component',
    targetSlug: 'washer-suspension',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-thermal-fuse-open',
    targetType: 'component',
    targetSlug: 'dryer-thermal-fuse',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-door-switch-failure',
    targetType: 'component',
    targetSlug: 'dryer-door-switch',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dryer-worn-drum-belt',
    targetType: 'component',
    targetSlug: 'dryer-drum-belt',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-float-switch-stuck',
    targetType: 'component',
    targetSlug: 'dishwasher-float-switch',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-drain-hose-leak',
    targetType: 'component',
    targetSlug: 'dishwasher-drain-hose',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-drain-hose-leak',
    targetType: 'component',
    targetSlug: 'washer-drain-hose',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'refrigerator-drip-pan-overflow',
    targetType: 'component',
    targetSlug: 'refrigerator-drip-pan',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'refrigerator-compressor-sealed-fault',
    targetType: 'component',
    targetSlug: 'refrigerator-compressor',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'washer-drain-pump-failure',
    targetType: 'component',
    targetSlug: 'washer-drain-pump',
    relation: 'affects',
    weight: 0.8,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'standing-water',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-drain-obstruction',
    relation: 'suggests',
    weight: 0.75,
    note: 'Very common when water remains after cycle',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'standing-water',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-drain-pump-failure',
    relation: 'suggests',
    weight: 0.60,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'standing-water',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-float-switch-stuck',
    relation: 'suggests',
    weight: 0.55,
    note: 'Float stuck down can leave standing water',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'wont-fill',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-float-switch-stuck',
    relation: 'suggests',
    weight: 0.65,
    note: 'Float stuck up can block fill',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'wont-drain',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-drain-obstruction',
    relation: 'suggests',
    weight: 0.80,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'grinding-noise',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-drain-pump-failure',
    relation: 'suggests',
    weight: 0.55,
    note: 'Debris in pump can cause grinding — dishwasher/washer only',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'grinding-noise',
    targetType: 'failure_mode',
    targetSlug: 'washer-drain-pump-failure',
    relation: 'suggests',
    weight: 0.55,
    note: 'Debris in washer pump can grind; not a dryer path',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'water-leak-on-floor',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-door-seal-leak',
    relation: 'suggests',
    weight: 0.65,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'water-leak-on-floor',
    targetType: 'failure_mode',
    targetSlug: 'dishwasher-drain-hose-leak',
    relation: 'suggests',
    weight: 0.60,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'water-leak-on-floor',
    targetType: 'failure_mode',
    targetSlug: 'washer-drain-hose-leak',
    relation: 'suggests',
    weight: 0.55,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'water-leak-on-floor',
    targetType: 'failure_mode',
    targetSlug: 'washer-supply-line-leak',
    relation: 'suggests',
    weight: 0.50,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'water-leak-on-floor',
    targetType: 'failure_mode',
    targetSlug: 'refrigerator-drip-pan-overflow',
    relation: 'suggests',
    weight: 0.50,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'wont-start',
    targetType: 'failure_mode',
    targetSlug: 'washer-lid-switch-failure',
    relation: 'suggests',
    weight: 0.70,
    note: 'Washer lid/door switch — not dryer belt',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'wont-start',
    targetType: 'failure_mode',
    targetSlug: 'dryer-door-switch-failure',
    relation: 'suggests',
    weight: 0.70,
    note: 'Nothing happens — door switch, not belt',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'drum-does-not-turn',
    targetType: 'failure_mode',
    targetSlug: 'dryer-worn-drum-belt',
    relation: 'suggests',
    weight: 0.75,
    note: 'Motor runs, drum does not',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'clothes-not-drying',
    targetType: 'failure_mode',
    targetSlug: 'dryer-thermal-fuse-open',
    relation: 'suggests',
    weight: 0.55,
    note: 'Open fuse after overheat; honest fuse failure mode',
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'clothes-not-drying',
    targetType: 'failure_mode',
    targetSlug: 'dryer-lint-buildup',
    relation: 'suggests',
    weight: 0.80,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'not-cooling',
    targetType: 'failure_mode',
    targetSlug: 'refrigerator-dirty-condenser-coils',
    relation: 'suggests',
    weight: 0.70,
  ),
  const KgSeedEdge(
    sourceType: 'symptom',
    sourceSlug: 'not-cooling',
    targetType: 'failure_mode',
    targetSlug: 'refrigerator-compressor-sealed-fault',
    relation: 'suggests',
    weight: 0.25,
    note: 'Professional/sealed only — never beginner DIY ranking',
  ),
  const KgSeedEdge(
    sourceType: 'failure_mode',
    sourceSlug: 'dishwasher-drain-obstruction',
    targetType: 'symptom',
    targetSlug: 'standing-water',
    relation: 'produces',
    weight: 0.75,
    note: 'Authored produces pair, not a seeder-forced mirror of every edge',
  ),
];

/// Backward-compatible name. Prefer [kgMvpEdges].
final kgMvpSuggestEdges = kgMvpEdges;
